---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-pip
    state: present
  become: yes

- name: Create a network RZ2
  docker_network:
    name: rz2

- name: Install pip docker
  pip:
    name: 
      - docker
      - docker-compose
    state: present

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: |
    curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
